package edu.persistence.model;

// Generated Mar 10, 2015 10:56:57 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Author generated by hbm2java
 */
@Entity
@Table(name = "author", schema = "public")
public class Author implements java.io.Serializable {

	private long id;
	private String firstName;
	private String lastName;
	private Set<BookByAuthor> bookByAuthors = new HashSet<BookByAuthor>(0);

	public Author() {
	}

	public Author(long id, String firstName, String lastName) {
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
	}

	public Author(long id, String firstName, String lastName,
			Set<BookByAuthor> bookByAuthors) {
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
		this.bookByAuthors = bookByAuthors;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "first_name", nullable = false, length = 20)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", nullable = false, length = 30)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "author")
	public Set<BookByAuthor> getBookByAuthors() {
		return this.bookByAuthors;
	}

	public void setBookByAuthors(Set<BookByAuthor> bookByAuthors) {
		this.bookByAuthors = bookByAuthors;
	}

}
