package edu.persistence.model;

// Generated Mar 10, 2015 10:56:57 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BookByCategoryId generated by hbm2java
 */
@Embeddable
public class BookByCategoryId implements java.io.Serializable {

	private Long categoryId;
	private Long bookId;

	public BookByCategoryId() {
	}

	public BookByCategoryId(Long categoryId, Long bookId) {
		this.categoryId = categoryId;
		this.bookId = bookId;
	}

	@Column(name = "category_id")
	public Long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "book_id")
	public Long getBookId() {
		return this.bookId;
	}

	public void setBookId(Long bookId) {
		this.bookId = bookId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BookByCategoryId))
			return false;
		BookByCategoryId castOther = (BookByCategoryId) other;

		return ((this.getCategoryId() == castOther.getCategoryId()) || (this
				.getCategoryId() != null && castOther.getCategoryId() != null && this
				.getCategoryId().equals(castOther.getCategoryId())))
				&& ((this.getBookId() == castOther.getBookId()) || (this
						.getBookId() != null && castOther.getBookId() != null && this
						.getBookId().equals(castOther.getBookId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCategoryId() == null ? 0 : this.getCategoryId()
						.hashCode());
		result = 37 * result
				+ (getBookId() == null ? 0 : this.getBookId().hashCode());
		return result;
	}

}
