package edu.persistence.model;

// Generated Mar 10, 2015 10:56:57 AM by Hibernate Tools 3.4.0.CR1

import java.time.LocalDate;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "book", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "isbn"))
public class Book implements java.io.Serializable {

	private long id;
	private String isbn;
	private String title;
	private LocalDate publicationDate;
	private Set<BookByCategory> bookByCategories = new HashSet<BookByCategory>(
			0);
	private Set<BookAtLibrary> bookAtLibraries = new HashSet<BookAtLibrary>(0);
	private Set<BookByAuthor> bookByAuthors = new HashSet<BookByAuthor>(0);

	public Book() {
	}

	public Book(long id, String isbn, String title, LocalDate publicationDate) {
		this.id = id;
		this.isbn = isbn;
		this.title = title;
		this.publicationDate = publicationDate;
	}

	public Book(long id, String isbn, String title, LocalDate publicationDate,
			Set<BookByCategory> bookByCategories,
			Set<BookAtLibrary> bookAtLibraries, Set<BookByAuthor> bookByAuthors) {
		this.id = id;
		this.isbn = isbn;
		this.title = title;
		this.publicationDate = publicationDate;
		this.bookByCategories = bookByCategories;
		this.bookAtLibraries = bookAtLibraries;
		this.bookByAuthors = bookByAuthors;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "isbn", unique = true, nullable = false, length = 13)
	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	@Column(name = "title", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "publication_date", nullable = false, length = 29)
	public Date getPublicationDate() {
		return this.publicationDate;
	}

	public void setPublicationDate(Date publicationDate) {
		this.publicationDate = publicationDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "book")
	public Set<BookByCategory> getBookByCategories() {
		return this.bookByCategories;
	}

	public void setBookByCategories(Set<BookByCategory> bookByCategories) {
		this.bookByCategories = bookByCategories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "book")
	public Set<BookAtLibrary> getBookAtLibraries() {
		return this.bookAtLibraries;
	}

	public void setBookAtLibraries(Set<BookAtLibrary> bookAtLibraries) {
		this.bookAtLibraries = bookAtLibraries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "book")
	public Set<BookByAuthor> getBookByAuthors() {
		return this.bookByAuthors;
	}

	public void setBookByAuthors(Set<BookByAuthor> bookByAuthors) {
		this.bookByAuthors = bookByAuthors;
	}

}
