package edu.persistence.model;

// Generated Mar 10, 2015 10:56:57 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BookByCategory generated by hbm2java
 */
@Entity
@Table(name = "book_by_category", schema = "public")
public class BookByCategory implements java.io.Serializable {

	private BookByCategoryId id;
	private Book book;
	private Category category;

	public BookByCategory() {
	}

	public BookByCategory(BookByCategoryId id) {
		this.id = id;
	}

	public BookByCategory(BookByCategoryId id, Book book, Category category) {
		this.id = id;
		this.book = book;
		this.category = category;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "categoryId", column = @Column(name = "category_id")),
			@AttributeOverride(name = "bookId", column = @Column(name = "book_id")) })
	public BookByCategoryId getId() {
		return this.id;
	}

	public void setId(BookByCategoryId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "book_id", insertable = false, updatable = false)
	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id", insertable = false, updatable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

}
