package edu.persistence.model;

// Generated Mar 10, 2015 10:56:57 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BookByAuthorId generated by hbm2java
 */
@Embeddable
public class BookByAuthorId implements java.io.Serializable {

	private Long authorId;
	private Long bookId;

	public BookByAuthorId() {
	}

	public BookByAuthorId(Long authorId, Long bookId) {
		this.authorId = authorId;
		this.bookId = bookId;
	}

	@Column(name = "author_id")
	public Long getAuthorId() {
		return this.authorId;
	}

	public void setAuthorId(Long authorId) {
		this.authorId = authorId;
	}

	@Column(name = "book_id")
	public Long getBookId() {
		return this.bookId;
	}

	public void setBookId(Long bookId) {
		this.bookId = bookId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BookByAuthorId))
			return false;
		BookByAuthorId castOther = (BookByAuthorId) other;

		return ((this.getAuthorId() == castOther.getAuthorId()) || (this
				.getAuthorId() != null && castOther.getAuthorId() != null && this
				.getAuthorId().equals(castOther.getAuthorId())))
				&& ((this.getBookId() == castOther.getBookId()) || (this
						.getBookId() != null && castOther.getBookId() != null && this
						.getBookId().equals(castOther.getBookId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getAuthorId() == null ? 0 : this.getAuthorId().hashCode());
		result = 37 * result
				+ (getBookId() == null ? 0 : this.getBookId().hashCode());
		return result;
	}

}
