package edu.persistence.model;

// Generated Mar 10, 2015 10:56:57 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category", schema = "public")
public class Category implements java.io.Serializable {

	private long id;
	private String categoryName;
	private Set<BookByCategory> bookByCategories = new HashSet<BookByCategory>(
			0);

	public Category() {
	}

	public Category(long id, String categoryName) {
		this.id = id;
		this.categoryName = categoryName;
	}

	public Category(long id, String categoryName,
			Set<BookByCategory> bookByCategories) {
		this.id = id;
		this.categoryName = categoryName;
		this.bookByCategories = bookByCategories;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "category_name", nullable = false, length = 50)
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	public Set<BookByCategory> getBookByCategories() {
		return this.bookByCategories;
	}

	public void setBookByCategories(Set<BookByCategory> bookByCategories) {
		this.bookByCategories = bookByCategories;
	}

}
