package edu.persistence.model;

// Generated Mar 10, 2015 10:56:57 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Library generated by hbm2java
 */
@Entity
@Table(name = "library", schema = "public")
public class Library implements java.io.Serializable {

	private long id;
	private Address address;
	private String libaryName;
	private Set<BookAtLibrary> bookAtLibraries = new HashSet<BookAtLibrary>(0);

	public Library() {
	}

	public Library(long id, String libaryName) {
		this.id = id;
		this.libaryName = libaryName;
	}

	public Library(long id, Address address, String libaryName,
			Set<BookAtLibrary> bookAtLibraries) {
		this.id = id;
		this.address = address;
		this.libaryName = libaryName;
		this.bookAtLibraries = bookAtLibraries;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "address_id")
	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	@Column(name = "libary_name", nullable = false, length = 50)
	public String getLibaryName() {
		return this.libaryName;
	}

	public void setLibaryName(String libaryName) {
		this.libaryName = libaryName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "library")
	public Set<BookAtLibrary> getBookAtLibraries() {
		return this.bookAtLibraries;
	}

	public void setBookAtLibraries(Set<BookAtLibrary> bookAtLibraries) {
		this.bookAtLibraries = bookAtLibraries;
	}

}
